### ISSUE TITLE
Multimodal Learning with Transformers: A Survey, Peng Xu et al.

### ISSUE THREAD

**Issue by PengBoXiangShang** [Yutong-Zhou-cv/Awesome-Multimodality#3]
Thanks for this list.

This paper has been accepted by IEEE TPAMI. 

Could you please update it?  Many thanks.

**Comment by Yutong-Zhou-cv** [comment]
Thanks for sharing. Your excellent paper has been updated.

**Comment by PengBoXiangShang** [comment]
> 

Many thanks.
